exclude = ["**/*__pycache__", "**/*egg-info", "**/docs", "**/tests", "**/.venv"]
interfaces = []
layers = ["register", "predicate", "trace", "typedefs"]
source_roots = ["src"]

[[modules]]
depends_on = []
layer = "typedefs"
path = "predylogic.typedefs"

[[modules]]
depends_on = ["predylogic.typedefs", "predylogic.predicate"]
layer = "register"
path = "predylogic.register"

[[modules]]
depends_on = ["predylogic.typedefs"]
layer = "trace"
path = "predylogic.trace"

[[modules]]
depends_on = ["predylogic.trace", "predylogic.typedefs"]
layer = "predicate"
path = "predylogic.predicate"
