exclude = ["**/*__pycache__", "**/*egg-info", "**/docs", "**/tests", "**/.venv"]
ignore_type_checking_imports = true
interfaces = []
layers = ["register", "rule_engine", "predicate", "trace", "typedefs"]
source_roots = ["src"]

[[modules]]
depends_on = []
layer = "typedefs"
path = "predylogic.typedefs"

[[modules]]
depends_on = []
layer = "register"
path = "predylogic.register"

[[modules]]
depends_on = []
layer = "trace"
path = "predylogic.trace"

[[modules]]
depends_on = []
layer = "predicate"
path = "predylogic.predicate"

[[modules]]
depends_on = []
layer = "rule_engine"
path = "predylogic.rule_engine"
