name: python-ci.yml
on:
  push:
    branches: [ "main" ]
    paths:
      - 'sdks/python/src/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/python-ci.yml'
  pull_request:
    types: [ opened, synchronize, ready_for_review ]
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  quality-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdks/python
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Run checks
        run: just check

  tests-and-type-check:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
      fail-fast: false
    defaults:
      run:
        shell: bash
        working-directory: sdks/python
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: uv run pytest tests --cov=src --cov-config=pyproject.toml --cov-report=xml

      - name: Check typing
        run: uv run ty check

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: ./sdks/python/coverage.xml
          flags: python
          fail_ci_if_error: true

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Check if documentation can be built
        run: uv run --project=sdks/python mkdocs build -s
