name: python-benchmark.yml
on:
  push:
    branches:
      - "main"
    paths:
      - "sdks/python/src/**"
      - "sdks/python/benchmarks/**"
      - ".github/workflows/python-benchmark.yml"
  pull_request:
    paths:
      - "sdks/python/src/**"
      - "sdks/python/benchmarks/**"
      - ".github/workflows/python-benchmark.yml"
    types: [ opened, synchronize, ready_for_review ]
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run CodSpeed
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdks/python
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: "3.13"

      - name: Run Benchmark with CodSpeed
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: |
            cd sdks/python && uv run pytest benchmarks/ -k "current" --codspeed
